# -------------------------------------------------------------------------
# Supplementary Study: ROBU Blockwise Resampling Budget (Computation)
# -------------------------------------------------------------------------

library(robustbase)
library(mvnfast)

# Source algorithm and main data generation scripts
# Note: Execute from the root of the repository
source("R/irwls.R")
source("R/robu.R")
source("simulations/generate_data.R")

set.seed(0)

# __________________________
# 1. Simulation Parameters
# __________________________

n.obs <- 1500      
p.vars <- 400      
cont.vec <- c(0.20, 0.30) 
n.reps <- 50              

# Calculate optimal block size
k.blocks <- max(1, floor(p.vars / 10))

# Create directories for outputs if they don't exist
dir.create("simulations/results", recursive = TRUE, showWarnings = FALSE)

# __________________________
# 2. Control Configurations
# __________________________

# A. Full Budget Control (Used in main manuscript simulations)
nResample_full <- 5000
control_full <- lmrob.control(
  method = "MM", 
  fast.s.large.n = Inf, 
  k.max = 5000,
  nResample = nResample_full,
  k.m_s = 2000,
  max.it = 1000,
  refine.tol = 1e-5
)

# B. Distributed Budget Control (Matching Section 3 recommendations)
nResample_dist <- ceiling(5000 / k.blocks) 
control_dist <- lmrob.control(
  method = "MM", 
  fast.s.large.n = Inf, 
  k.max = 5000,
  nResample = nResample_dist,
  k.m_s = 2000,
  max.it = 1000,
  refine.tol = 1e-5
)

# _______________________
# 3. Evaluation Helper
# _______________________

eval_robu <- function(name, dat, k.blocks, r_control, m_control) {
  t0 <- proc.time()[["elapsed"]]
  
  fit <- tryCatch({
    suppressWarnings(
      robu(x = dat$x, y = dat$y, k = k.blocks, 
           robu.control = r_control, m.control = m_control)
    )
  }, error = function(e) NULL)
  
  t1 <- proc.time()[["elapsed"]]
  
  if (is.null(fit)) {
    return(data.frame(Method = name, MSE = NA, Time = t1 - t0, TP = NA, FP = NA))
  }
  
  mse <- sum((fit$coefficients - dat$beta.true)^2)
  
  # Outlier detection (TP/FP rates)
  wt <- fit$rweights
  if (is.null(wt)) wt <- fit$weights
  
  if (!is.null(wt)) {
    tp <- sum(wt == 0 & dat$out.ind == 1)
    fp <- sum(wt == 0 & dat$out.ind == 0)
  } else {
    tp <- NA; fp <- NA
  }
  
  data.frame(Method = name, MSE = mse, Time = t1 - t0, TP = tp, FP = fp)
}

# ______________
# 4. Main Loop
# ______________

results <- data.frame()
raw_results_file <- "simulations/results/robu_budget_supplement_raw.rds"

cat("Starting ROBU Budget Study (Reps = 50)...\n")

for (eps in cont.vec) {
  cat("\n======================================================\n")
  cat(sprintf("Testing p = %d | eps = %.2f \n", p.vars, eps))
  cat("======================================================\n")
  
  for (r in 1:n.reps) {
    # Generate high-leverage outliers
    dat <- generate_data(n = n.obs, p = p.vars, cont.prop = eps, leverage = TRUE)
    
    # Run ROBU Full Budget
    res_full <- eval_robu("ROBU (Full Budget)", dat, k.blocks, 
                          r_control = control_full, 
                          m_control = control_full)
    
    # Run ROBU Distributed Budget
    # Pass 'dist' to robu.control (for block S-estimators) 
    # Pass 'full' to m.control (for the global final MM step)
    res_dist <- eval_robu("ROBU (Distributed Budget)", dat, k.blocks, 
                          r_control = control_dist, 
                          m_control = control_full)
    
    res_full$Eps <- eps; res_full$Rep <- r
    res_dist$Eps <- eps; res_dist$Rep <- r
    
    results <- rbind(results, res_full, res_dist)
    cat(sprintf("  Rep %02d done. Full Time: %5.2fs | Distributed Time: %5.2fs\n", 
                r, res_full$Time, res_dist$Time))
    
    # Continuously save raw results in case of interruption
    saveRDS(results, raw_results_file)
  }
}

cat("\nSimulation complete. Raw data saved to:", raw_results_file, "\n")

# _______________________________________
# 5. Summarize and Save Numerical Tables
# _______________________________________

cat("\nAggregating numerical summary...\n")

# Calculate Mean and Standard Deviation for MSE and Time
summary_table <- aggregate(
  cbind(MSE, Time) ~ Method + Eps, 
  data = results, 
  FUN = function(x) c(Mean = mean(x, na.rm = TRUE), SD = sd(x, na.rm = TRUE))
)

# Flatten the matrix-columns generated by aggregate() for clean saving
summary_flat <- do.call(data.frame, summary_table)

# Save the summary table
summary_file <- "simulations/results/robu_budget_supplement_summary.rds"
saveRDS(summary_flat, summary_file)

cat("Numerical summary saved to:", summary_file, "\n")
cat("Run complete.\n")